### ISSUE TITLE
.remove help

### ISSUE THREAD

**Issue by tewksbum** [ManuelDeLeon/ReactiveArray#10]
hi - not to be dense, but I'm struggling to .remove an item....

off the past example, I modeled:

_ta.remove(function(item) { return item._id === this._id });

where:
 _ta = my reactive array
_id = the "key" for the array and is a simple integer (i.e., 1, 2, 3, ...)

Am I missing something?

**Comment by ManuelDeLeon** [comment]
The problem is probably `this._id`

**Comment by tewksbum** [comment]
I'm sorry. Newbie here. Not sure what you mean?  In console I can confirm both the .-I'd values are returning "15".   Is this a type issue?  One a string the other an int?  Suggestions on how to fix?

In the only published examples I can find on remove - it shows remove just "mortensen". Do I need to identify which field in the array part?  I'm pretty sure ivebtried just passing in 15 and that didn't work. 

All I'm trying to do is delete an entry out of the array.  

Thanks in advance!

**Comment by ManuelDeLeon** [comment]
try:

``` js
var idToRemove = this._id; // or however you're getting the id to remove.
_ta.remove(function(item) { return item._id === idToRemove });
```

**Comment by tewksbum** [comment]
Voila!  Merci Beaucoup!
