### ISSUE TITLE
Sort example (native)

### ISSUE THREAD

**Issue by molinto** [ManuelDeLeon/ReactiveArray#11]
Hi, thanks for the wrapper :)

I'm trying to create an activity feed, but using 6 different collections.  They all push to:

```
var allSingle = new ReactiveArray();
```

But I need to sort by **created**  value within the objects added to the reactive array.  I've tried to use lodash to no avail:

```
Template.timelineWidget.helpers({
       allSingleActivity: function() {
        allSingle = _.map(_.sortByOrder(allSingle.array(), ['created'], ['asc']), _.values);
        return allSingle.list();
    }

});
```

I've noticed the **sort([compareFunction])** in the docs (http://reactivearray.meteor.com/#nativeBk). but wasn't sure what to do here.  Any help greatly appreciated.  

Thanks
Sharry

PS - The allSingle array has to be reactive to update the template

**Comment by ManuelDeLeon** [comment]
Its a regular array sort:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FGlobal_Objects%2FArray%2Fsort

**Comment by molinto** [comment]
Thanks dude:

```
 allSingleActivity: function() {
        var date_sort_desc = function (date1, date2) {
            if (date1.created > date2.created) return -1;
            if (date1.created < date2.created) return 1;
            return 0;
        };
        allSingle.sort(date_sort_desc);
        return allSingle.list();
    }
```
