### ISSUE TITLE
Site is down!

### ISSUE THREAD

**Issue by developeron29** [ManuelDeLeon/ReactiveArray#12]
http://reactivearray.meteor.com/ is down

**Comment by ManuelDeLeon** [comment]
That's an issue with Meteor hosting.

**Comment by DTSchroeder** [comment]
Is it maybe possible to include the documentation in the README?

**Comment by ManuelDeLeon** [comment]
Sure, but it's at the bottom of my priority list. If you give me a read me
I'll be happy to update it.

**Comment by meetmagdalene** [comment]
I found a workaround to still view the site using a web archive "wayback machine": http://web.archive.org/web/20150605044930/http://reactivearray.meteor.com/
Snippet taken June 5th, 2015.

**Comment by martpie** [comment]
Thanks @meetmagdalene, works fine. But It would be great to fix the website.
