### ISSUE TITLE
Updating a single value with splice causes entire array to update

### ISSUE THREAD

**Issue by Shelagh-Lewins** [ManuelDeLeon/ReactiveArray#13]
Is there any way to update a single value in an array without causing the entire array to re-render?

At present I'm using splice to set a value, and this is triggering all values in the array to be re-rendered.

**Comment by ManuelDeLeon** [comment]
Use a client side collection instead.

**Comment by Shelagh-Lewins** [comment]
I tried that and couldn't make that work.

Each user may have many grids, and can create and destroy them, so I couldn't figure out how to handle one collection per grid.

Arrays in MongoDB are not modelled in minimongo, so I couldn't use arrays in the collection.

Storing a document with key-value pairs to record row and column was very slow.

**Comment by Shelagh-Lewins** [comment]
When you say "client side collection", do you mean that would be significantly faster than a regular server-and-client collection?

**Comment by ManuelDeLeon** [comment]
It doesn't need to go to the server and everything it entails so it would
be a lot better.

**Comment by dpatte** [comment]
I am seeing a similar situation. The meteor specs imply that if a single value is updated in a collection that is being displayed in blaze, then only that value is updated in the display. But when I have a reactive array that is a copy of a collection, and i update a single value in the reactive array, all elements of the array are redrawn.
In my case my reactive array is a copy of the local minimongo collection, but sorted in a business-specific manner. Neither minimongo nor mongo seem to provide the feature for me to request the records to be sorted in the order I need.

**Comment by ManuelDeLeon** [comment]
@dpatte 
You need to use a client side collection instead. What you're asking for is essentially a cursor. There's no point in adding cursor functionality when minimongo does that out of the box.

**Comment by dpatte** [comment]
True. But a collection is not guaranteed to be in order like an array, nor does it allow splicing, so I cannot use a collection either.

**Comment by ManuelDeLeon** [comment]
I can't imagine what you're doing but you could add an index field.

I'm sorry but this just isn't meant to be used as a cursor.
