### ISSUE TITLE
Extra items at beginning of ReactiveArray

### ISSUE THREAD

**Issue by arggh** [ManuelDeLeon/ReactiveArray#19]
After updating to ViewModel 6.3.6 and ReactiveArray v1.0.8, all code using ReactiveArrays seems to be broken.

For example, iterating over an array of 6 items, there's suddenly two items more:

The first item in the array is an array containing the actual items I was expecting, the second item is of type `Tracker.Dependency`, followed by the actual array items, totaling in length 8 instead of expected 6.

Is there some breaking changes expected between 1.0.6 and 1.08?

**Comment by ManuelDeLeon** [comment]
I'll work on it. Meteor 1.6 changed Coffeescript and I've been dealing with
problems ever since.

**Comment by arggh** [comment]
Thanks for the heads up.

We've had a truckload of trouble too ever since 1.6.1.1. I've been trying to get rid of every possibe package using CoffeeScript v1, and there's a few... 

Let me know if you need any help testing versions or otherwise, I'm here around the clock basically until we get this nightmare under control.

**Comment by ManuelDeLeon** [comment]
I `meteor add manuel:reactivearray` and it's working as expected:

```js
var a = new ReactiveArray() // undefined
for(let e of a){ console.log(e) } // -nothing-
a.push("A") // 1
for(let e of a){ console.log(e) } // A
```

**Comment by arggh** [comment]
Maybe it's only occurring when used in ViewModels?

Reproduction: https://github.com/arggh/viewmodel-reactivearray-issue

<details>
<summary>Sample output from reproduction</summary>

```
Items SHOULD be: ['one', 'two', 'three']
Items REALLY is: [["one","two","three"],{"_dependentsById":{"3":{"stopped":false,"invalidated":false,"firstRun":true,"_id":3,"_onInvalidateCallbacks":[null],"_onStopCallbacks":[],"_parent":null,"_recomputing":false}}},"one","two","three"],
Items ITERATED: [ ["one","two","three"], {"_dependentsById":{"3":{"stopped":false,"invalidated":false,"firstRun":false,"_id":3,"_onInvalidateCallbacks":[null,null],"_onStopCallbacks":[null],"_parent":null,"_recomputing":false},"4":{"stopped":false,"invalidated":false,"firstRun":false,"_id":4,"_onInvalidateCallbacks":[null],"_onStopCallbacks":[null],"_parent":null,"_recomputing":false}}}, "one", "two", "three", ]
Items size SHOULD be: 3 Items size REALLY is: 5
```
</details>

**Comment by arggh** [comment]
Dropping ViewModel and only using ReactiveArray, the array contents are as expected.

https://github.com/arggh/viewmodel-reactivearray-issue/tree/array-only

Should I move this issue to ViewModel repository?

**Comment by ManuelDeLeon** [comment]
Nah, keep here. I'll deal with it today.

**Comment by ManuelDeLeon** [comment]
Pick up reactivearray 1.0.9 and viewmodel 6.3.7

Should be fine now.

**Comment by arggh** [comment]
Confirmed, extraneous items disappeared, thank you!
