### ISSUE TITLE
Cannot use reactiveArray.list() in cursor

### ISSUE THREAD

**Issue by rclai** [ManuelDeLeon/ReactiveArray#2]
Great package by the way.

``` js
var test = new ReactiveList(['asdf', 'fdas', 'aw3f5wa']);
var thing = Thing.findOne({ _id: { $in: test.list() } });
Uncaught Error: $in needs an array
```

Edit:
Using `test.array()` works though. Is this intentional?

**Comment by ManuelDeLeon** [comment]
That's normal. `.list()` returns a `ReactiveArray` object. `.array()` returns an `Array` object. ReactiveArray inherits from array so it should work in a perfect world but the selector doesn't accept anything other than a true array (bummer).

**Comment by rclai** [comment]
Oh alright, cool.
