### ISSUE TITLE
Reactive array not reactive when value of property changes

### ISSUE THREAD

**Issue by Karabi-Choudhury** [ManuelDeLeon/ReactiveArray#8]
Hi,

Suppose i have an array
var arr = new ReactiveArray([
  {id: '1', name: 'a'},
  {id: '2', name: 'b'}
]).
If any change is made in the "name" property of id="2" , will any helper referring the reactive array run again.
For me it is not running .Is there any way that my helper runs once more on value change of property

**Comment by ManuelDeLeon** [comment]
That's because the array isn't changing (it still has the same references to the objects). There are many ways of "reactifying" objects but in your case it seems like you want to use an in memory collection:

``` js
var people = new Mongo.Collection(null);
```

**Comment by dpatte** [comment]
I also see a similar situation. If I change a particular element of a reactive array by assigning a new object to it, it is not reactive. It only seems to be reactive if I splice the new object into the array overwriting the old object in that particular position.

**Comment by ManuelDeLeon** [comment]
Same answer: use a client side collection.

**Comment by avalanche1** [comment]
> Same answer: use a client side collection.

Why haven't I even thought in that direction?? so simple...
